### ISSUE TITLE
[docker compose] etcd cluster via docker compose

### ISSUE THREAD

**Issue by redink** [redink/redink_toys#6]
docker-compose.yml

```
version: '2'
services:
    etcd1:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd1
        hostname: etcd1
        networks:
            - redink_erlang_cluster
        ports:
            - "49380:2380"
            - "49379:2379"
        environment:
            ETCD_NAME: etcd1
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
            ETCD_LISTEN_PEER_URLS: http://etcd1:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd1:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

    etcd2:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd2
        hostname: etcd2
        networks:
            - redink_erlang_cluster
        ports:
            - "49280:2380"
            - "49279:2379"
        environment:
            ETCD_NAME: etcd2
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
            ETCD_LISTEN_PEER_URLS: http://etcd2:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd2:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

    etcd3:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd3
        hostname: etcd3
        networks:
            - redink_erlang_cluster
        ports:
            - "49180:2380"
            - "49179:2379"
        environment:
            ETCD_NAME: etcd3
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
            ETCD_LISTEN_PEER_URLS: http://etcd3:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd3:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

networks:
    redink_erlang_cluster:
        driver: bridge
```
