### ISSUE TITLE
[erlang compose] erlang cluster with etcd via docker compose

### ISSUE THREAD

**Issue by redink** [redink/redink_toys#7]
docker-compose.yml

```
version: '2'
services:
    erl1:
        image: redink/centos_erlang
        restart: always
        container_name: erl1
        hostname: erl1
        networks:
            - redink_erlang_cluster
        ports:
            - "49001:22"
            - "49101:4369"
        environment:
            TERM: xterm

    erl2:
        image: redink/centos_erlang
        restart: always
        container_name: erl2
        hostname: erl2
        networks:
            - redink_erlang_cluster
        ports:
            - "49002:22"
            - "49102:4369"
        environment:
            TERM: xterm

    erl3:
        image: redink/centos_erlang
        restart: always
        container_name: erl3
        hostname: erl3
        networks:
            - redink_erlang_cluster
        ports:
            - "49003:22"
            - "49103:4369"
        environment:
            TERM: xterm

    erl4:
        image: redink/centos_erlang
        restart: always
        container_name: erl4
        hostname: erl4
        networks:
            - redink_erlang_cluster
        ports:
            - "49004:22"
            - "49104:4369"
        environment:
            TERM: xterm

    erl5:
        image: redink/centos_erlang
        restart: always
        container_name: erl5
        hostname: erl5
        networks:
            - redink_erlang_cluster
        ports:
            - "49005:22"
            - "49105:4369"
        environment:
            TERM: xterm

    erl6:
        image: redink/centos_erlang
        restart: always
        container_name: erl6
        hostname: erl6
        networks:
            - redink_erlang_cluster
        ports:
            - "49006:22"
            - "49106:4369"
        environment:
            TERM: xterm

    erl7:
        image: redink/centos_erlang
        restart: always
        container_name: erl7
        hostname: erl7
        networks:
            - redink_erlang_cluster
        ports:
            - "49007:22"
            - "49107:4369"
        environment:
            TERM: xterm

    erl8:
        image: redink/centos_erlang
        restart: always
        container_name: erl8
        hostname: erl8
        networks:
            - redink_erlang_cluster
        ports:
            - "49008:22"
            - "49108:4369"
        environment:
            TERM: xterm

    erl9:
        image: redink/centos_erlang
        restart: always
        container_name: erl9
        hostname: erl9
        networks:
            - redink_erlang_cluster
        ports:
            - "49009:22"
            - "49109:4369"

    etcd1:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd1
        hostname: etcd1
        networks:
            - redink_erlang_cluster
        ports:
            - "49380:2380"
            - "49379:2379"
        environment:
            ETCD_NAME: etcd1
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
            ETCD_LISTEN_PEER_URLS: http://etcd1:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd1:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

    etcd2:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd2
        hostname: etcd2
        networks:
            - redink_erlang_cluster
        ports:
            - "49280:2380"
            - "49279:2379"
        environment:
            ETCD_NAME: etcd2
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
            ETCD_LISTEN_PEER_URLS: http://etcd2:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd2:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

    etcd3:
        image: quay.io/coreos/etcd
        restart: always
        container_name: etcd3
        hostname: etcd3
        networks:
            - redink_erlang_cluster
        ports:
            - "49180:2380"
            - "49179:2379"
        environment:
            ETCD_NAME: etcd3
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
            ETCD_LISTEN_PEER_URLS: http://etcd3:2380
            ETCD_LISTEN_CLIENT_URLS: http://etcd3:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
            ETCD_INITIAL_CLUSTER_TOKEN: etcd_cluster_1

networks:
    redink_erlang_cluster:
        driver: bridge
```
